### ISSUE TITLE
Errors thrown in pages other than family tree

### ISSUE THREAD

**Issue by cool-Blue** [cool-Blue/SO-Questions#3]
The main issue is that elements of the family tree page are still working in the other pages.  
The problem was that I had a listener on infoState.widthChange that tries to adjust the force layout to center the search result node and this was still active on the age page.
I put some defensive code in the listener to check if the force data is loaded.  I exposed the force data on the familytree object to allow this.

I'm not sure what your original code was like, but I wonder if changing it so that the familytree and familytreeController objects are only initialised when 
the #menu4familytree element in menue.js is clicked and adding propper shut-down code on #familytreecontentclose.click - or at least a sleep mode - would be a good idea.

**Comment by kwoxer** [comment]
Sorry could you explain when the error arises. For me it's fine right now without any error. And If you click the close button on the familytree it's intended to load the current page from the background. This is done because otherwhise the images from the xlink:href svg object are not working properly anymore. But please let me know if this issue here still exists. =)

**Comment by cool-Blue** [comment]
OK, this should be solved by the PR.  I was waiting for you to confirm.

I had to guess what the problem was so I just logged this error because I observed it in my previous version and I figured it was the one you were talking about, but I don't know for sure.

Just to check that it's ok, can you please explain exactly what errors you were talking about in your last comment on Stack Overflow?

**Comment by kwoxer** [comment]
You mean that comment? 

_Hey cool you really keeped on working on it man =) I just checked the diff to my current version. It seems that you did not use my latest version somehow =/. But as always I like the changes so I wanted to test it out. But anyways I your code is getting several issues on the method names. Did it work for you? Sad but I'm sure that we can get it running? I think comments are better here then on Github =)_
?
If yes that issue is now fixed here with your pull request =)

**Comment by cool-Blue** [comment]
OK, just to confirm: it was happening when you click on a region in one of the Age screens?  When the info panel opened correct?

**Comment by kwoxer** [comment]
No the issue was in the familytree. When I clicked an element of the suggestion box. =) But now it's all fine, don't worry.

**Comment by cool-Blue** [comment]
OK, I'll close this one then. :)
